name: Build Windows EXE

on:
  workflow_dispatch:

env:
  CI: true
  NODE_OPTIONS: --max-old-space-size=8192
  HUSKY: 0

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm@9
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts
      - name: Build workspace packages
        run: pnpm -r --filter '!ui-tars-desktop' build
      - name: Build app
        working-directory: apps/ui-tars
        run: |
          pnpm run build:dist
          npx electron-packager . "UI TARS" --platform=win32 --arch=x64 --out=out --overwrite --icon=resources/icon --prune=true
        env:
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
      - name: Upload app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: UI-TARS-Win64
          path: apps/ui-tars/out/UI TARS-win32-x64/
          if-no-files-found: error
